Bugfix for some cases where validator fails
nubank/fklearn pull request #208
Opened 2022-08-16 18:21 UTC by nicolas-behar

### Status
**IN DEVELOPMENT**

### Todo list
- [ ] Documentation
- [ ] Tests added and passed

### Background context
Depending on the data - if it has gaps that makes all the training start and end date be NaT, the validator function will break.

### Description of the changes proposed in the pull request
This PR should fix the mentioned issue by skipping the folds where there is no training or testing data and saving these failure logs. The changes will only take effect if "drop_empty_folds" is set to be True, otherwise, the implementation of this function will remain as it was before.

2022-08-18 20:31 UTC, GiulioCMSanto commented on src/fklearn/validation/validator.py
> +        if (len(train_index) <= 1 or len(test_indexes[0]) == 0) and drop_empty_folds:
The test_indexes is a list of indexes. A suggestion is the following:

```suggestion
        
        test_contains_null_folds = max(map(lambda x: len(x) == 0, test_indexes))
        train_fold_is_null = len(train_index) == 0

        if (train_fold_is_null or test_contains_null_folds) and drop_empty_folds:
```

2022-08-18 20:53 UTC, GiulioCMSanto commented on tests/validation/test_validator.py
> +data = pd.DataFrame({"rows": ["row1", "row2", "row3", "row4"]})
Maybe using a fixture here?

```suggestion
@pytest.fixture
def data():
    return pd.DataFrame({"rows": ["row1", "row2", "row3", "row4"]})
```

2022-08-18 20:53 UTC, GiulioCMSanto commented on tests/validation/test_validator.py
>  def test_validator_iteration():
```suggestion
def test_validator_iteration(data):
```

2022-08-18 20:53 UTC, GiulioCMSanto commented on tests/validation/test_validator.py
>  def test_parallel_validator():
```suggestion
def test_parallel_validator(data):
```

2022-08-18 20:57 UTC, GiulioCMSanto requested changes

2022-08-18 20:57 UTC, GiulioCMSanto commented on tests/validation/test_validator.py
>  def test_validator():
Great! I would suggest one more test, which is when the splitters provides a list of indexes for the testing index, i.e., fold = [train_index, list of test_index]

2022-08-19 17:19 UTC, GiulioCMSanto reviewed
I am getting an error in the following line when running the test_validator test:

https://github.com/nubank/fklearn/blob/bfdc44d40cb194907fc59f022ddd38daf7a2e7c9/src/fklearn/validation/validator.py#L211

It seems that the issue is the following:

Since you are using a lightgbm, in the zipped_log we have the training log which, in turns, have the lightgbm version (lightgbm._ _version _ _). However, lightgbm is not being imported, raising an exception.

2022-08-25 19:39 UTC, vinipd submitted a review, later dismissed
LGTM.

2022-08-25 20:09 UTC, GiulioCMSanto approved these changes

2022-08-25 20:24 UTC, nicolas-behar commented on CHANGELOG.md
> +## [2.1.1] - 2022-08-17
I will open a new PR with this bump and changelog, and include the S-Learner info also, since it was not bumped yet.

2022-08-25 20:29 UTC, GiulioCMSanto approved these changes

2022-08-25 21:04 UTC, nicolas-behar commented on CHANGELOG.md
> +## [2.1.1] - 2022-08-17
done it at https://github.com/nubank/fklearn/pull/210

2022-08-25 21:05 UTC, merged