Including LGBM parameters to lgbm_classification_learner
nubank/fklearn pull request #211
Opened 2022-09-02 22:47 UTC by nicolas-behar

### Status
**IN DEVELOPMENT**

### Todo list
- [ ] Documentation
- [ ] Tests added and passed
- [ ] Issue: closes #194 

### Background context
Some of the already implemented LGBM parameters can't be used by the lgbm_classification_learner function.

### Description of the changes proposed in the pull request
We are including these parameters by changing the lgbm.train call function with these parameters, that can be passed by the user if needed.

### Related PRs
https://github.com/nubank/fklearn/pull/197

2022-09-14 12:57 UTC, eduardodx requested changes

2022-09-14 12:57 UTC, eduardodx commented on src/fklearn/training/classification.py
> +    valid_sets :
Missing description.

2022-09-14 12:57 UTC, eduardodx commented on src/fklearn/training/classification.py
> +    valid_names :
Missing description.

2022-10-19 12:33 UTC, fabiofabris approved these changes

2022-10-19 12:35 UTC, eduardodx approved these changes
LGTM! 🚀

2022-10-19 12:36 UTC, merged